import { field, document } from 'nodedata/mongoose/decorators';
import { Types } from 'mongoose';
import { Strict } from 'nodedata/mongoose/enums';

export interface UserInterface {
    _id: string;
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    roles: any;
};


@document({ name: 'users', strict: Strict.false })
export class UserModel {

    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    email: string;

    @field()
    password: string;

    @field()
    firstName: string;

    @field()
    lastName: string;

    @field()
    phone: string;

    @field()
    dob: Date;

    @field()
    deactivated: boolean;

    roles: Array<string>;

    _links: any;

    constructor(userDto?: UserInterface) {
    }
}

export default UserModel;
