import { field, transient } from 'nodedata/mongoose/decorators';
import { jsonignore } from 'nodedata/core/decorators';
import { Types } from 'mongoose';
import { CrudEntity } from 'nodedata/core/dynamic/crud.entity';

export class BaseEntity extends CrudEntity {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    @jsonignore()
    parent: BaseEntity;

    @field()
    @jsonignore()
    children: Array<BaseEntity>;

    @transient()
    __selectedFindWhere: string;

    @transient()
    __partialLoaded: boolean;

    @field()
    batch: number;

    public getAllChildren(): Array<BaseEntity> {
        return this.children;
    }
}

export default BaseEntity;
